
/* Last Updated Dec. 23, 2024 */

/* TAG FOR WEBSOCKET TO SEND SIGNAL THAT BRACELETS SHOULD TRANSMIT THEIR LOCATIONS */
export const SEND_TRANSMIT_LOCATION_SIGNAL_TO_BRACELETS = "SEND_TRANSMIT_LOCATION_SIGNAL_TO_BRACELETS"

/* TAG FOR WEBSOCKET TO SEND EVACUATION INSTRUCTION TO BRACELETS */
export const SEND_EVACUATION_INSTRUCTION_TO_BRACELETS = "SEND_EVACUATION_INSTRUCTION_TO_BRACELETS"

/* TAG FOR WEBSOCKET TO RELAY THE RECEIVED LOCATION OF BRACELET TO THE CLIENT */
export const SEND_RECEIVED_LOCATION_TO_CLIENT = "SEND_RECEIVED_LOCATION_TO_CLIENT"

/* TAG FOR WEBSOCKET TO SEND TASKS FROM CLIENT TO RESCUERS BRACELETS */
export const SEND_TASK_TO_RESCUER = "SEND_TASK_TO_RESCUER"