
// RECEIVING CODES
export const LOCATION_FROM_USER = ""
export const LOCATION_FROM_RESCUER = ""
export const SOS_FROM_RESCUER= ""
export const TASK_ACKNOWLEDGEMENT_FROM_RESCUER= ""
export const TASK_STATUS_UPDATE_FROM_USER = ""
export const URGENCY_UPDATE_FROM_USER = ""

// TRANSMITTING CODES
export const START_LOCATION_TRANSMISSION_TO_TRU = ""
export const INSTRUCTION_TO_USER = ""
export const TASK_TO_RESCUER = ""