
# LoRa to Server
LOCATION_FROM_USER = "1"
LOCATION_FROM_USER_PY = "PY-1"
SOS_FROM_USER = "2"
SOS_FROM_USER_PY = "PY-2"
SOS_FROM_RESCUER = "3"
SOS_FROM_RESCUER_PY = "PY-3"
TASK_ACKNOWLEDGEMENT_FROM_RESCUER = "4"
TASK_ACKNOWLEDGEMENT_FROM_RESCUER_PY = "PY-4"
TASK_STATUS_UPDATE_FROM_RESCUER = "5"
TASK_STATUS_UPDATE_FROM_RESCUER_PY = "PY-5"
LOCATION_FROM_RESCUER = "6"
LOCATION_FROM_RESCUER_PY = "PY-6"

# Server to LoRa
START_LOCATION_TRANSMISSION_TO_TRU = "7"
START_LOCATION_TRANSMISSION_TO_TRU_PY = "PY-7"
INSTRUCTION_TO_USER = "8"
INSTRUCTION_TO_USER_PY = "PY-8"
TASK_TO_RESCUER = "9"
TASK_TO_RESCUER_PY = "PY-9"
