graphhopper:
  graph.location: ./graph-cache
  datareader.file: ./philippines-latest-2.osm.pbf
  profiles:
    - name: car
      vehicle: car
      weighting: fastest

server:
  applicationConnectors:
    - type: http
      port: 8989
  adminConnectors: []
