
/* Last Updated Dec. 23, 2024 */

// /* TAG FOR WEBSOCKET TO SEND SIGNAL THAT BRACELETS SHOULD TRANSMIT THEIR LOCATIONS */
// export const SEND_TRANSMIT_LOCATION_SIGNAL_TO_BRACELETS = "SEND_TRANSMIT_LOCATION_SIGNAL_TO_BRACELETS"

// /* TAG FOR WEBSOCKET TO SEND EVACUATION INSTRUCTION TO BRACELETS */
// export const SEND_EVACUATION_INSTRUCTION_TO_BRACELETS = "SEND_EVACUATION_INSTRUCTION_TO_BRACELETS"

// /* TAG FOR WEBSOCKET TO RELAY THE RECEIVED LOCATION OF BRACELET TO THE CLIENT */
// export const SEND_RECEIVED_LOCATION_TO_CLIENT = "SEND_RECEIVED_LOCATION_TO_CLIENT"

// /* TAG FOR WEBSOCKET TO SEND TASKS FROM CLIENT TO RESCUERS BRACELETS */
// export const SEND_TASK_TO_RESCUER = "SEND_TASK_TO_RESCUER"

// RECEIVING
export const LOCATION_FROM_USER = "1010"
export const LOCATION_FROM_USER_PY = "PY-1010"
export const SOS_FROM_RESCUER = "1030"
export const SOS_FROM_RESCUER_PY = "PY-1030"
export const SOS_FROM_USER = "1020"
export const SOS_FROM_USER_PY= "PY-1020"
export const TASK_ACKNOWLEDGEMENT_FROM_RESCUER = "1040"
export const TASK_ACKNOWLEDGEMENT_FROM_RESCUER_PY = "PY-1040"
export const TASK_STATUS_UPDATE_FROM_RESCUER = "1050"
export const TASK_STATUS_UPDATE_FROM_RESCUER_PY = "PY-1050"
export const URGENCY_UPDATE_FROM_USER = "1060"
export const URGENCY_UPDATE_FROM_USER_PY = "PY-1060"
export const LOCATION_FROM_RESCUER = "1070"
export const LOCATION_FROM_RESCUER_PY = "PY-1070"

// TRANSMITTING
export const START_LOCATION_TRANSMISSION_TO_TRU = "1080"
export const START_LOCATION_TRANSMISSION_TO_TRU_PY = "PY-1080"
export const INSTRUCTION_TO_USER = "1090"
export const INSTRUCTION_TO_USER_PY = "PY-1090"
export const TASK_TO_RESCUER = "10A0"
export const TASK_TO_RESCUER_PY = "PY-10A0"

