"use strict";
/* Last Updated Mar. 18, 2025 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OBSTACLE_TO_RESCUER_PY = exports.OBSTACLE_TO_RESCUER = exports.TASK_TO_RESCUER_PY = exports.TASK_TO_RESCUER = exports.INSTRUCTION_TO_USER_PY = exports.INSTRUCTION_TO_USER = exports.START_LOCATION_TRANSMISSION_TO_TRU_PY = exports.START_LOCATION_TRANSMISSION_TO_TRU = exports.LOCATION_FROM_RESCUER_PY = exports.LOCATION_FROM_RESCUER = exports.TASK_STATUS_UPDATE_FROM_RESCUER_PY = exports.TASK_STATUS_UPDATE_FROM_RESCUER = exports.TASK_ACKNOWLEDGEMENT_FROM_RESCUER_PY = exports.TASK_ACKNOWLEDGEMENT_FROM_RESCUER = exports.SOS_FROM_RESCUER_PY = exports.SOS_FROM_RESCUER = exports.SOS_FROM_USER_PY = exports.SOS_FROM_USER = exports.LOCATION_FROM_USER_PY = exports.LOCATION_FROM_USER = void 0;
// /* TAG FOR WEBSOCKET TO SEND SIGNAL THAT BRACELETS SHOULD TRANSMIT THEIR LOCATIONS */
// export const SEND_TRANSMIT_LOCATION_SIGNAL_TO_BRACELETS = "SEND_TRANSMIT_LOCATION_SIGNAL_TO_BRACELETS"
// /* TAG FOR WEBSOCKET TO SEND EVACUATION INSTRUCTION TO BRACELETS */
// export const SEND_EVACUATION_INSTRUCTION_TO_BRACELETS = "SEND_EVACUATION_INSTRUCTION_TO_BRACELETS"
// /* TAG FOR WEBSOCKET TO RELAY THE RECEIVED LOCATION OF BRACELET TO THE CLIENT */
// export const SEND_RECEIVED_LOCATION_TO_CLIENT = "SEND_RECEIVED_LOCATION_TO_CLIENT"
// /* TAG FOR WEBSOCKET TO SEND TASKS FROM CLIENT TO RESCUERS BRACELETS */
// export const SEND_TASK_TO_RESCUER = "SEND_TASK_TO_RESCUER"
// RECEIVING
exports.LOCATION_FROM_USER = "1";
exports.LOCATION_FROM_USER_PY = "PY-1";
exports.SOS_FROM_USER = "2";
exports.SOS_FROM_USER_PY = "PY-2";
exports.SOS_FROM_RESCUER = "3";
exports.SOS_FROM_RESCUER_PY = "PY-3";
exports.TASK_ACKNOWLEDGEMENT_FROM_RESCUER = "4";
exports.TASK_ACKNOWLEDGEMENT_FROM_RESCUER_PY = "PY-4";
exports.TASK_STATUS_UPDATE_FROM_RESCUER = "5";
exports.TASK_STATUS_UPDATE_FROM_RESCUER_PY = "PY-5";
exports.LOCATION_FROM_RESCUER = "6";
exports.LOCATION_FROM_RESCUER_PY = "PY-6";
// TRANSMITTING
exports.START_LOCATION_TRANSMISSION_TO_TRU = "7";
exports.START_LOCATION_TRANSMISSION_TO_TRU_PY = "PY-7";
exports.INSTRUCTION_TO_USER = "8";
exports.INSTRUCTION_TO_USER_PY = "PY-8";
exports.TASK_TO_RESCUER = "9";
exports.TASK_TO_RESCUER_PY = "PY-9";
exports.OBSTACLE_TO_RESCUER = "B";
exports.OBSTACLE_TO_RESCUER_PY = "PY-B";
