
/* Last Updated Mar. 18, 2025 */

// /* TAG FOR WEBSOCKET TO SEND SIGNAL THAT BRACELETS SHOULD TRANSMIT THEIR LOCATIONS */
// export const SEND_TRANSMIT_LOCATION_SIGNAL_TO_BRACELETS = "SEND_TRANSMIT_LOCATION_SIGNAL_TO_BRACELETS"

// /* TAG FOR WEBSOCKET TO SEND EVACUATION INSTRUCTION TO BRACELETS */
// export const SEND_EVACUATION_INSTRUCTION_TO_BRACELETS = "SEND_EVACUATION_INSTRUCTION_TO_BRACELETS"

// /* TAG FOR WEBSOCKET TO RELAY THE RECEIVED LOCATION OF BRACELET TO THE CLIENT */
// export const SEND_RECEIVED_LOCATION_TO_CLIENT = "SEND_RECEIVED_LOCATION_TO_CLIENT"

// /* TAG FOR WEBSOCKET TO SEND TASKS FROM CLIENT TO RESCUERS BRACELETS */
// export const SEND_TASK_TO_RESCUER = "SEND_TASK_TO_RESCUER"

// RECEIVING
export const LOCATION_FROM_USER = "1"
export const LOCATION_FROM_USER_PY = "PY-1"
export const SOS_FROM_USER = "2"
export const SOS_FROM_USER_PY= "PY-2"
export const SOS_FROM_RESCUER = "3"
export const SOS_FROM_RESCUER_PY = "PY-3"
export const TASK_ACKNOWLEDGEMENT_FROM_RESCUER = "4"
export const TASK_ACKNOWLEDGEMENT_FROM_RESCUER_PY = "PY-4"
export const TASK_STATUS_UPDATE_FROM_RESCUER = "5"
export const TASK_STATUS_UPDATE_FROM_RESCUER_PY = "PY-5"
export const LOCATION_FROM_RESCUER = "6"
export const LOCATION_FROM_RESCUER_PY = "PY-6"

// TRANSMITTING
export const START_LOCATION_TRANSMISSION_TO_TRU = "7"
export const START_LOCATION_TRANSMISSION_TO_TRU_PY = "PY-7"
export const INSTRUCTION_TO_USER = "8"
export const INSTRUCTION_TO_USER_PY = "PY-8"
export const TASK_TO_RESCUER = "9"
export const TASK_TO_RESCUER_PY = "PY-9"
export const OBSTACLE_TO_RESCUER = "B"
export const OBSTACLE_TO_RESCUER_PY = "PY-B"

