
export const OWNERS_TAG = "OWNERS_DATA_TABLE"
export const BRACELETS_TAG = "BRACELETS_DATA_TABLE"
export const RESCUERS_TAG = "RESCUERS_DATA_TABLE"
export const MISSIONS_TAG = "MISSIONS_DATA_TABLE"
export const EVACUATION_CENTERS_TAG = "EVACUATION_CENTERS_DATA_TABLE"