
/* Last Updated Dec. 23, 2024 */

/* TAG FOR WEBSOCKET TO SEND SIGNAL THAT BRACELETS SHOULD TRANSMIT THEIR LOCATIONS */
export const SEND_TRANSMIT_LOCATION_SIGNAL_TO_BRACELETS = "SEND_TRANSMIT_LOCATION_SIGNAL_TO_BRACELETS"

/* TAG FOR WEBSOCKET TO SEND EVACUATION INSTRUCTION TO BRACELETS */
export const SEND_EVACUATION_INSTRUCTION_TO_BRACELETS = "SEND_EVACUATION_INSTRUCTION_TO_BRACELETS"

/* TAG FOR WEBSOCKET TO RELAY THE RECEIVED LOCATION OF BRACELET TO THE CLIENT */
export const SEND_RECEIVED_LOCATION_TO_CLIENT = "SEND_RECEIVED_LOCATION_TO_CLIENT"

/* TAG FOR WEBSOCKET TO SEND TASKS FROM CLIENT TO RESCUERS BRACELETS */
export const SEND_TASK_TO_RESCUER = "SEND_TASK_TO_RESCUER"



export const LOCATION_FROM_USER = "0000001"
export const SOS_FROM_RESCUER = "0000010"
export const SOS_FROM_USER = "0000011"
export const TASK_ACKNOWLEDGEMENT_FROM_RESCUER = "0000100"
export const TASK_STATUS_UPDATE_FROM_RESCUER = "0000101"
export const URGENCY_UPDATE_FROM_USER = "0000110"
export const LOCATION_FROM_RESCUER = "0000111"

export const START_LOCATION_TRANSMISSION_TO_TRU = "0001000"
export const INSTRUCTION_TO_USER = "0001001"
export const TASK_TO_RESCUER = "0001010"
